dataset:
  train:
    dir:
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-01-09-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-01-23-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-01-27-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-06-14-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-07-15-06"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-01-17-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-01-27-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-03-16-02"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/train/augmented/2022-06-28-01"
    format: "h5"
    labeled: false
  valid:
    dir:
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-02-16-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-04-05-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-07-20-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-03-22-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-04-12-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-07-26-01"
    format: "h5"
    labeled: false
  test:
    dir:
      # - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-02-16-04"
      # - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-04-05-01"
      # - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-07-20-01"
      # - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-03-22-01"
      #- "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-04-12-04"
      #- "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/valid/2022-07-26-01"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/test/2022-04-14-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/test/2022-04-18-04"
      - "/home/alicia/data_personal/regnet_dataset/euler-gpu_size-v1/test/2022-08-02-01"
    format: "h5"
    labeled: false
  type: paired # paired / unpaired / grouped
  moving_image_shape: [208,96,56]
  fixed_image_shape: [208,96,56]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "local" # value should be local / global / unet
    num_channel_initial: 16 # number of initial channel in local net, controls the size of the network
    extract_levels: [0, 1, 2, 3]
  loss:
    image:
      name: "lncc"
      kernel_size: 16
      weight: 1.
    regularization:
      weight: 0.02
      name: "nonrigid"
      img_size: [208,96,56]
  preprocess:
    data_augmentation:
      name: "affine"
    batch_size: 4
    shuffle_buffer_num_batch: 2
    num_parallel_calls: -1
  optimizer:
    name: "Adam"
    learning_rate: 1.0e-3
  epochs: 20000
  save_period: 1
